version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 5000
    networks:
      - appnet

  web:
    image: kizaing/kavita:latest
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "5012:5000"
    volumes:
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/manga:/manga
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/comics:/comics
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/books:/books
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/data:/kavita/config
    networks:
      - appnet

networks:
  appnet:
