version: "3.7"

services:
  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    volumes:
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/manga:/manga            # Aggiorna il volume per Umbrel
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/comics:/comics          # Aggiorna il volume per Umbrel
      - /data/umbrel-os/home/umbrel/umbrel/data/storage/downloads/Kavita/books:/books            # Aggiorna il volume per Umbrel
      - /mnt/data/kavita/config:/kavita/config   # Umbrel richiede di salvare i dati in /mnt/data/
    environment:
      - TZ=Europe/Rome  # Imposta il tuo fuso orario
    ports:
      - "5000:5000" # Cambia la porta esterna (la prima 5000) se c'è conflitto con altre app
    restart: unless-stopped

networks:
  default:
    external:
      name: umbrel_main_network
